### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by RochaLAJ** [pwnwriter/heliumbar#8]
You asked on reddit what kind of features the end user want. I am not the one person that you asked for but i would like to contribute somehow. [post](https://www.reddit.com/r/hyprland/comments/15vhgdc/comment/jwzla1g/?utm_source=share&utm_medium=web2x&context=3)

**Current bars**
1. Easy to theme like i3status-rust (See: https://github.com/greshake/i3status-rust) 
2. Modularity like waybar as long-term goal (See: https://github.com/Alexays/Waybar)
3. Two or three "pretty" profiles that works out of the box like gBar (See: https://github.com/scorpion-26/gBar) 
4. Less dependency as possible. (See: https://github.com/Alexays/Waybar/issues/2415)
5. Clear and open documentation (See: https://github.com/WayfireWM/wayfire/wiki) 

Why i am not using i3status-rust or waybar?

1. i3status-rust is made to run with i3/Sway (i'm using Hyprland)
2. Fmt update broke waybar, i had to keep fmt on a previous version.

**Features (personal)**
1. Tray 
2. Dock mode where we can associated apps

You may find some inspiration here: https://www.droptopfour.com/ 

Right now i am using gBar but it's not accessible to theme or change like waybar. Too much stuff built-in.

**Comment by pwnwriter** [comment]
Sure, thank you for your suggestions. I'll definitely take a closer look into them!  :)
